In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset)

In [5]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_female', 'sex_male',
       'smoker_no', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0      19  27.900         0        True     False      False        True
1      18  33.770         1       False      True       True       False
2      28  33.000         3       False      True       True       False
3      33  22.705         0       False      True       True       False
4      32  28.880         0       False      True       True       False
...   ...     ...       ...         ...       ...        ...         ...
1333   50  30.970         3       False      True       True       False
1334   18  31.920         0        True     False       True       False
1335   18  36.850         0        True     False       True       False
1336   21  25.800         0        True     False       True       False
1337   61  29.070         0        True     False      False        True

[1338 rows x 7 columns]

In [9]:
dependent=dataset[['charges']]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [26]:
from sklearn.tree import DecisionTreeRegressor
from math import sqrt
max_features_val = int(sqrt(x_train.shape[1]))
regressor=DecisionTreeRegressor(criterion='poisson', splitter='random',max_features='sqrt')
regressor=regressor.fit(x_train,y_train)

In [27]:
y_pred=regressor.predict(x_test)

In [28]:
from sklearn.metrics import r2_score
r2_score=r2_score(y_test,y_pred)

In [29]:
r2_score

0.6949286113680647